stages:
  - generate
  - test

variables:
  IMAGE: "riot/riotbuild:2025.07"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

workflow:
  rules:
    # Restrict the number of times the pipeline runs to save resources/limits
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        # Specific merge request configurations for coveralls
        CI_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        CI_PULL_REQUEST: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == 'push'
      when: never  # Avoid running the pipeline twice (push + merge request)
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG

# This job discovers subdirectories under $TEST_DIR and emits child pipelines YAML
# as artifacts. Each discovered directory becomes a separate job.
generate_tests:
  stage: generate
  before_script:
    - chmod +x ./ci/generate_tests_pipeline.sh
    - chmod +x ./ci/generate_compile_tests_pipeline.sh
  script:
    - ./ci/generate_tests_pipeline.sh tests-pipeline.yml
    - ./ci/generate_compile_tests_pipeline.sh compile-tests-pipeline.yml
  artifacts:
    paths:
      - tests-pipeline.yml
      - compile-tests-pipeline.yml
    expire_in: 1h
  cache:
    key: "$CI_PROJECT_PATH-$CI_COMMIT_REF_SLUG-submodules"
    paths:
      - nodes/firmware/RIOT/

run_subtests:
  stage: test
  needs:
    - job: generate_tests
      artifacts: true
  trigger:
    include:
      - artifact: tests-pipeline.yml
        job: generate_tests
    strategy: depend
  rules:
    - when: always

run_compilations:
  stage: test
  needs:
    - job: generate_tests
      artifacts: true
  trigger:
    include:
      - artifact: compile-tests-pipeline.yml
        job: generate_tests
    strategy: depend
  rules:
    - when: always
