M48
; DRILL file {KiCad 9.0.2} date 2025-06-24T11:01:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-24T11:01:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X99.0Y-59.5
X104.0Y-59.5
T2
X109.0Y-71.5
X118.5Y-58.5
X118.5Y-110.0
M30
