#!/usr/bin/env python3
"""Generate Ed25519 key pairs for devices and the server.

Mirrors the firmware key-distro/util_scripts/generate_prod_keys.py pattern
for the backend database.

Outputs:
  - SQL INSERT statements for the device_public_keys and server_key tables
  - C header files compatible with firmware key-distro format
  - JSON format for backend API provisioning

Usage:
  python3 generate_ed25519_keys.py --device sensegate-1
  python3 generate_ed25519_keys.py --device sensegate-1 --device sensemate-1
  python3 generate_ed25519_keys.py --server --kid backend-server
  python3 generate_ed25519_keys.py --server --kid backend-server --output-dir ./keys
"""

import argparse
import json
import os
import sys
from pathlib import Path

try:
    from nacl.bindings import crypto_sign_seed_keypair
    HAS_NACL = True
except ImportError:
    HAS_NACL = False

try:
    import secrets
except ImportError:
    secrets = None


def generate_ed25519_keypair(seed: bytes | None = None) -> tuple[bytes, bytes]:
    """Generate an Ed25519 key pair.

    Returns (private_key_seed, public_key) where private_key_seed is 64 bytes
    (seed) and public_key is 32 bytes.
    """
    if HAS_NACL:
        if seed is None:
            seed = os.urandom(32)
        pk, sk = crypto_sign_seed_keypair(seed)
        # crypto_sign_seed_keypair returns (public, secret_with_seed_prefix)
        # nacl expects 64-byte secret key: seed[0:32] + public[0:32]
        sk_full = seed + pk
        return sk_full, pk
    else:
        # Fallback: use PyNaCl if available
        from nacl.signing import SigningKey
        if seed:
            sk = SigningKey(seed)
        else:
            sk = SigningKey.generate()
        vk = sk.verify_key
        return sk.encode(), vk.encode()


def format_sql_device(kid: str, public_key: bytes) -> str:
    key_hex = public_key.hex()
    return (
        f"INSERT INTO device_public_keys (kid, public_key)\n"
        f"VALUES ('{kid}', decode('{key_hex}', 'hex'))\n"
        f"ON CONFLICT (kid) DO UPDATE SET public_key = EXCLUDED.public_key, updated_at = NOW();\n"
    )


def format_sql_server(kid: str, private_key: bytes, public_key: bytes) -> str:
    priv_hex = private_key.hex()
    pub_hex = public_key.hex()
    return (
        f"INSERT INTO server_key (id, kid, private_key, public_key)\n"
        f"VALUES (1, '{kid}', decode('{priv_hex}', 'hex'), decode('{pub_hex}', 'hex'))\n"
        f"ON CONFLICT (id) DO UPDATE SET kid = EXCLUDED.kid, private_key = EXCLUDED.private_key,\n"
        f"    public_key = EXCLUDED.public_key, updated_at = NOW();\n"
    )


def format_c_header_device(kid: str, public_key: bytes) -> str:
    key_bytes = ", ".join(f"0x{b:02x}" for b in public_key)
    guard = f"PUBLIC_KEY_{kid.upper().replace('-', '_')}_H"
    return f"""#ifndef {guard}
#define {guard}

static const uint8_t {kid.replace('-', '_')}_public_key[32] = {{
  {key_bytes}
}};

#endif /* {guard} */
"""


def format_json_device(kid: str, public_key: bytes) -> str:
    return json.dumps({
        "kid": kid,
        "publicKey": public_key.hex(),
        "publicKeyBytes": list(public_key),
    }, indent=2)


def format_json_server(kid: str, private_key: bytes, public_key: bytes) -> str:
    return json.dumps({
        "kid": kid,
        "privateKey": private_key.hex(),
        "publicKey": public_key.hex(),
        "publicKeyBytes": list(public_key),
    }, indent=2)


def main():
    parser = argparse.ArgumentParser(description="Generate Ed25519 key pairs for devices/server")
    parser.add_argument("--device", "-d", action="append", dest="devices",
                        help="Device KID (e.g. sensegate-1). Can be specified multiple times.")
    parser.add_argument("--server", action="store_true",
                        help="Generate a server key pair")
    parser.add_argument("--kid", default="server",
                        help="KID for the server key (default: server)")
    parser.add_argument("--output-dir", "-o", default=None,
                        help="Output directory for C header files")
    parser.add_argument("--sql", action="store_true",
                        help="Output SQL statements to stdout")
    parser.add_argument("--json", action="store_true",
                        help="Output as JSON to stdout")
    parser.add_argument("--seed", default=None,
                        help="Fixed 32-byte hex seed for deterministic keys (testing only)")

    args = parser.parse_args()

    seed_bytes = None
    if args.seed:
        seed_bytes = bytes.fromhex(args.seed)
        if len(seed_bytes) != 32:
            parser.error("Seed must be exactly 32 bytes (64 hex chars)")

    if args.sql or (not args.output_dir and not args.json):
        print("-- Ed25519 key provisioning SQL")
        print("-- Generated by generate_ed25519_keys.py")
        print()

    if args.devices:
        for kid in args.devices:
            priv, pub = generate_ed25519_keypair(seed_bytes)
            if args.output_dir:
                out_dir = Path(args.output_dir)
                out_dir.mkdir(parents=True, exist_ok=True)
                header_path = out_dir / f"public_key_{kid}.h"
                with open(header_path, "w") as f:
                    f.write(format_c_header_device(kid, pub))
                print(f"Wrote C header: {header_path}")

            if args.sql or (not args.output_dir and not args.json):
                print(format_sql_device(kid, pub))

            if args.json:
                print(format_json_device(kid, pub))

    if args.server:
        priv, pub = generate_ed25519_keypair(seed_bytes)
        if args.output_dir:
            out_dir = Path(args.output_dir)
            out_dir.mkdir(parents=True, exist_ok=True)
            header_path = out_dir / f"server_key_{args.kid}.h"
            with open(header_path, "w") as f:
                f.write(format_c_header_device(args.kid, pub))
            print(f"Wrote C header: {header_path}")

        if args.sql or (not args.output_dir and not args.json):
            print(format_sql_server(args.kid, priv, pub))

        if args.json:
            print(format_json_server(args.kid, priv, pub))


if __name__ == "__main__":
    main()
