M48
; DRILL file KiCad 10.0.3 date 2026-06-16T11:49:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-16T11:49:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X92.17Y-73.62
X92.17Y-78.62
T2
X92.19Y-86.11
M30
