USEPKG += flashdb

# if flashdb_mtd is not selected manually, select the VFS backend instead
ifeq (,$(filter flashdb_mtd,$(USEMODULE)))
  USEMODULE += flashdb_vfs
endif


# enable key-value database
USEMODULE += flashdb_kvdb

USEMODULE += base64

USEMODULE += store_service
