CFLAGS += -DCONFIG_LORAMAC_APP_EUI_DEFAULT=\"0012005600089000\"
CFLAGS += -DCONFIG_LORAMAC_DEV_EUI_DEFAULT=\"FFFFFFFFFFFFFFFF\"
CFLAGS += -DCONFIG_LORAMAC_APP_KEY_DEFAULT=\"FFFFFFFFFFFFFFFFFFFFFFFFFFFFAABB\"
